### ISSUE TITLE
兄弟，我想请问一下你那个代码中的表情是怎么输入进去的？非常感谢

### ISSUE THREAD

**Issue by lizheng3401** [hellohve/hve#1]

**Comment by aoxiaoqiang** [comment]
:books:

:one: github本身就支持emoji表情的。
:two: [git commit emoji 使用指南](https://github.com/liuchengxu/git-commit-emoji-cn)
:three: [完整 github markdown emoji 标签列表](https://gist.github.com/rxaviers/7360908)

**Comment by lizheng3401** [comment]
恩恩，学习了，之前还不知道这个呢，非常感谢
